name: Deploy Backend to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
        
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
    
    - name: Deploy backend and create .env file
      run: |
        ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} '
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          cd ~/book-library-backend && 
          git pull && 
          npm i && 
          
          # Always create/update .env file with latest values from GitHub secrets
          echo "Updating .env file with latest environment variables..."
          cat > .env << EOL
          MONGODB_URI=${{ secrets.MONGODB_URI }}
          PORT=${{ secrets.PORT || 3001 }}
          AWS_REGION=${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # Add any other environment variables you need
          EOL
          
          pm2 restart npm || pm2 start npm -- start
        ' 